services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    network_mode: "service:gluetun"
    # ports:
    #   - 3000:3000
    env_file:
      - aiostreams.env
    volumes:
      - ./aio_data:/app/data
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 15m
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      - gluetun
    
  stremthru:
    container_name: stremthru
    image: muniftanjim/stremthru:latest
    network_mode: "service:gluetun"
    # ports:
    #  - 8787:8080
    env_file:
      - stremthru.env
    restart: unless-stopped
    volumes:
      - ./strem_data:/app/data
    depends_on:
      - gluetun

  postgres:
    image: postgres:16.6-alpine
    network_mode: "service:gluetun"
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_DB: stremthru
      POSTGRES_USER: fullmetal
      POSTGRES_PASSWORD: fullmetal
    restart: always
    volumes:
      - ./strem_data/postgres:/var/lib/postgresql/data
    depends_on:
      - gluetun
  
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun-p2:/gluetun
      - ./wg0.conf:/gluetun/wireguard/wg0.conf
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
      - 3000:3000
      - 8787:8080
      - 8088:5432
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Kolkata
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - DOT=off